package desafioWebsiteImportSelenium;

//Generated by Selenium IDE
import java.util.HashMap;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class cadastrarUsuario {
private WebDriver driver;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void cadastrarusurio() {
 driver.get("http://www.inmrobo.tk/accounts/login/");
 driver.findElement(By.linkText("Cadastre-se")).click();
 driver.findElement(By.name("username")).sendKeys("vitorteste2");
 driver.findElement(By.name("pass")).sendKeys("123456");
 driver.findElement(By.name("confirmpass")).sendKeys("123456");
 driver.findElement(By.cssSelector(".login100-form-btn")).click();
}
}
