package desafioWebsiteImportSelenium;

import java.util.HashMap;
import java.util.List;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
public class loginfluxofuncionario {
private WebDriver driver;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void loginFluxoFuncionario() {
 driver.get("http://www.inmrobo.tk/accounts/login/");
 driver.findElement(By.name("username")).click();
 driver.findElement(By.name("username")).sendKeys("vitorteste2");
 driver.findElement(By.name("pass")).click();
 driver.findElement(By.name("pass")).sendKeys("123456");
 driver.findElement(By.cssSelector(".login100-form-btn")).click();  //Login
 String URL = driver.getCurrentUrl();
 Assert.assertEquals(URL, "http://www.inmrobo.tk/empregados/" );	//verifica se login foi feito e acessou a tela inicial
 
 
 driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
 driver.findElement(By.id("inputNome")).click();
 driver.findElement(By.id("inputNome")).sendKeys("vitorTeste");
 driver.findElement(By.id("cpf")).sendKeys("031.239.835-28");
 driver.findElement(By.id("slctSexo")).click();
 {
   WebElement dropdown = driver.findElement(By.id("slctSexo"));
   dropdown.findElement(By.xpath("//option[. = 'Masculino']")).click();
 }
 driver.findElement(By.cssSelector("option:nth-child(4)")).click();
 driver.findElement(By.id("inputAdmissao")).sendKeys("16/12/2020");
 driver.findElement(By.id("inputCargo")).sendKeys("analista de teste");
 driver.findElement(By.id("dinheiro")).sendKeys("4.200,00");
 driver.findElement(By.id("clt")).click();
 driver.findElement(By.cssSelector(".cadastrar-form-btn")).click(); //cadastrar funcionário
 {
   List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
   assert(elements.size() > 0);
 }
 driver.findElement(By.cssSelector("label > input")).click();
 driver.findElement(By.cssSelector("label > input")).sendKeys("031.239.835-28"); //busca funcionário cadastrado
 driver.findElement(By.cssSelector(".odd .btn-warning > .fa")).click();			//solicita edição do funcionário
 driver.findElement(By.id("inputNome")).sendKeys("Editado");
 driver.findElement(By.id("inputCargo")).sendKeys("Editado");
 driver.findElement(By.cssSelector(".cadastrar-form-btn")).click();				//Confirma edição do funcionário
 {
   List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
   assert(elements.size() > 0);
 }
 driver.findElement(By.cssSelector("label > input")).click();
 driver.findElement(By.cssSelector("label > input")).sendKeys("031.239.835-28"); //busca funcionário
 driver.findElement(By.cssSelector(".odd #delete-btn > .fa")).click();			//Exclui funcionário selecionado
 {
   List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
   assert(elements.size() > 0);
 }
 driver.findElement(By.cssSelector(".nav-item:nth-child(3) > .nav-link")).click();
}
}

